spring:
  datasource:
    druid:
      url: jdbc:mysql:///blog
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml
  type-aliases-package: cn.edu.scau.blog.**
